{{- if eq .Values.global.pluginsmanager.data.operation "upload" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Release.Name}}-{{ randAlphaNum 5 | lower }}
  labels:
    {{- include "pluginsmanager.labels" . | nindent 4 }}
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 3600  # Cleanup of jobs from key/value store after 100 sec
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pluginsmanager.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ include "pluginsmanager.serviceAccountName" . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      {{- range $name, $plugin := .Values.plugins }}
      - name: {{ $name }}-image-extraction
        image: {{ $.Values.global.pluginsmanager.data.SOURCE_REGISTRY }}/stratosphere/container-image-extractor
        imagePullPolicy: Always
        env:
        - name: SOURCE_REGISTRY
          value: {{ $.Values.global.pluginsmanager.data.SOURCE_REGISTRY }}/tci
        - name: SOURCE_DOCKER_IMAGE
          value: "{{ $.Values.global.pluginsmanager.data.SOURCE_REGISTRY }}/tci/{{ $name }}:{{ $plugin.tag }}"
        - name: IMAGE_TEMP_DIR
          value: "/opt/tmp/{{ $name }}/"
        - name: SOURCE_DIRS
          value: "/opt/tibco/bw-contribution/"
        - name: TARGET_DIRS
          value: "/efs/bw-contribution"
        - name: LOG_LEVEL
          value: debug
        volumeMounts:
        - mountPath: /efs
          name: shared-vol
      {{- end }}
      volumes:
        - name: shared-vol
          persistentVolumeClaim:
            {{- if .Values.volumes.pluginsmanager.persistentVolumeClaim.create }}
            claimName: {{ include "pluginsmanager.storage.pvc.name" . }}
            {{- else }}
            claimName: {{ .Values.volumes.pluginsmanager.existingClaim }}
            {{- end }}

{{- end }}
