{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pluginsmanager.fullname" . }}
  labels:
    {{- include "pluginsmanager.labels" . | nindent 4 }}
data:
{{- end }}
