apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orchestrator.fullname" . }}
  namespace: {{ .Values.global.orchestrator.data.namespace }}
  labels:
    {{- include "orchestrator.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "orchestrator.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 1
    type: RollingUpdate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "orchestrator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ include "orchestrator.serviceAccountName" . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: server
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          #image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          image: {{ .Values.global.orchestrator.image.registry }}/tci/tci-orchestrator:{{ .Values.global.orchestrator.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.volumes.orchestrator.volumePath }}
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: v1/liveness
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- range $filename, $content :=  .Values.config }}
            {{- if $content }}
            - name: {{ $filename }}
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-serviceconfig
                  key: {{ $filename }}
            {{- end }}
            {{- end }}
        {{- if .Values.global.orchestrator.deploymanager.enabled }}
        - name: deploymanager
          image: {{ .Values.global.orchestrator.deploymanager.image.registry }}/tci/tci-app-proxy:{{ .Values.global.orchestrator.deploymanager.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.global.orchestrator.deploymanager.resources | nindent 12 }}
          volumeMounts:
            - name: configs
              mountPath: /configs
          env:
            - name: DEPLOY_MANAGER_SERVICE
              value: "true"
            - name: APPS_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-serviceconfig
                  key: APPS_NAMESPACE
          ports:
            - containerPort: 7830
              protocol: TCP
              name: deploymanager
        {{- end }}
        {{- if .Values.global.orchestrator.logging.enabled }}
        - name: fluent-bit
          image: {{ .Values.global.orchestrator.logging.image.registry }}/tci/fluent-bit:{{ .Values.global.orchestrator.logging.image.registry.tag }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          resources:
            {{- toYaml .Values.global.orchestrator.deploymanager.resources | nindent 12 }}
          securityContext:
            privileged: true
          ports:
            - containerPort: 2020
          env:
            - name: ACCOUNT_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-serviceconfig
                  key: SERVICE_LOGSERVER_HOST
            - name: SERVICE_LOGSERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-serviceconfig
                  key: SERVICE_LOGSERVER_HOST

            - name: SERVICE_LOGSERVER_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-serviceconfig
                  key: SERVICE_LOGSERVER_USER

            - name: LOGSERVER_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-serviceconfig
                  key: LOGSERVER_PASSWORD

            - name: SERVICE_LOGSERVER_INDEX
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-serviceconfig
                  key: SERVICE_LOGSERVER_INDEX

            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TIBCO_INTERNAL_INTERCOM_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-serviceconfig
                  key: TIBCO_INTERNAL_INTERCOM_URL
            - name: POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: CONTAINER_NAME
              value: {{ .Chart.Name }}

          volumeMounts:
            - name: dockercontainerlogs
              mountPath: /var/lib/docker/containers/
            - name: podlogs
              mountPath: /var/log/pods
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/
        terminationGracePeriodSeconds: 10
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "orchestrator.storage.pvc.name" . }}
        {{- if .Values.global.orchestrator.logging.enabled }}
        - name: dockercontainerlogs
            hostPath:
              path: /var/lib/docker/containers/
        - name: podlogs
          hostPath:
            path: /var/log/pods
        - name: fluent-bit-config
          configMap:
            name: {{ include "orchestrator.fluentConf" . }}
        {{- end }}
