apiVersion: v2
name: logproxy
version: 1.0.0
appVersion: "1.0.0"
description: TIBCO Platform Dataplane Infrastructre Core -- Log Proxy
home: https://github.com/tibco/tp-log-proxy.git
icon: https://pbs.twimg.com/profile_images/1064638558110007296/K6HqaXwh_400x400.jpg
maintainers:
  - name: TIBCO CIC Compute Dev Team
    email: compute-dev@tibco.com
