{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pluginsdownloader.fullname" . }}
  labels:
    {{- include "pluginsdownloader.labels" . | nindent 4 }}
data:
{{- end }}
