apiVersion: v1
kind: Secret
metadata:
  name: {{ include "o11y-service.fullname" . }}
  labels:
    {{- include "o11y-service.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  sc: "test"