apiVersion: v1
kind: Secret
metadata:
  name: {{ include "o11y-service.fullname" . }}
  labels:
    {{- include "o11y-service.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  logserver-proxy-password: {{ default "" .Values.secret.logserver.proxy.password | b64enc | quote }}
  promserver-proxy-password: {{ default "" .Values.secret.promserver.proxy.password | b64enc | quote }}
  promserver-exporter-token: {{ default "" .Values.secret.promserver.exporter.token | b64enc | quote }}