{{- if eq .Values.global.o11yservice.serviceAccount "" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "o11y-service.sa" . }}
  labels:
    {{- include "o11y-service.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
