capabilityId: BWCE
version:
  - 1
  - 0
  - 0
recipe:
  helmCharts:
    - name: bwprovisioner
      namespace: ${NAMESPACE}
      repository:
        git:
          host: https://github.com/sasahoo-tibco/tp-integration.git
          path: /helm/charts/bwprovisioner
          branch: main
      values:
        - content: |
            global:
              bwprovisioner:
                data:
                  namspace: ${NAMESPACE}
                image:
                  registry: 664529841144.dkr.ecr.us-west-2.amazonaws.com
                  tag: 183
            ingress:
              annotations:
                haproxy.org/cors-enable: "true"
                haproxy.org/load-balance: leastconn
                haproxy.org/src-ip-header: X-Real-IP
                haproxy.org/timeout-http-request: 600s
                ingress.kubernetes.io/rewrite-target: /
                meta.helm.sh/release-name: bwprovisioner
              enabled: true
              hostsOverride: false
            config:
              SOURCE_REGISTRY: "664529841144.dkr.ecr.us-west-2.amazonaws.com"
      flags:
        install: true
        createNamespace: false
        dependencyUpdate: true
    - name: artifactmanager
      namespace: ${NAMESPACE}
      repository:
        git:
          host: https://github.com/sasahoo-tibco/tp-integration.git
          path: /helm/charts/artifactmanager
          branch: main
      values:
        - content: |
            global:
              artifactmanager:
                data:
                  namspace: ${NAMESPACE}
                image:
                  registry: 664529841144.dkr.ecr.us-west-2.amazonaws.com
                  tag: 26
            ingress:
              annotations:
                haproxy.org/cors-enable: "true"
                haproxy.org/load-balance: leastconn
                haproxy.org/src-ip-header: X-Real-IP
                haproxy.org/timeout-http-request: 600s
                ingress.kubernetes.io/rewrite-target: /
                meta.helm.sh/release-name: artifactmanager
              enabled: true
              hostsOverride: false
            volumes:
              artifactmanager:
                persistentVolumeClaim:
                  create: true
      flags:
        install: true
        createNamespace: false
        dependencyUpdate: true
    - name: distributed-lock-operator
      namespace: ${NAMESPACE}
      repository:
        git:
          host: https://github.com/sasahoo-tibco/tp-integration.git
          path: /helm/charts/distributed-lock-operator
          branch: main
      values:
        - content: |
            global:
              image:
                registry: 664529841144.dkr.ecr.us-west-2.amazonaws.com
                tag: 58
      flags:
        install: true
        createNamespace: false
        dependencyUpdate: true
        isDevTesting: false
status: deployed
region: us-west-2
eula: true
tags:
  - Tag1
  - Tag2

