capabilityId: BWCE
version:
  - 1
  - 0
  - 0
recipe:
  helmCharts:
    - name: bwprovisioner
      namespace: ${NAMESPACE}
      repository:
        git:
          host: https://github.com/sasahoo-tibco/tp-integration.git
          path: /helm/charts/bwprovisioner
          branch: main
      values:
        - content: |
            global:
              bwprovisioner:
                data:
                  namspace: ${NAMESPACE}
                image:
                  registry: 664529841144.dkr.ecr.us-west-2.amazonaws.com
                  tag: 123
            ingress:
              annotations:
                haproxy.org/cors-enable: "true"
                haproxy.org/load-balance: leastconn
                haproxy.org/src-ip-header: X-Real-IP
                haproxy.org/timeout-http-request: 600s
                ingress.kubernetes.io/rewrite-target: /
                meta.helm.sh/release-name: bwprovisioner
                meta.helm.sh/release-namespace: ${NAMESPACE}
              enabled: true
              hostsOverride: false
            volumes:
              bwprovisioner:
                persistentVolumeClaim:
                  create: true
                  storageClassName: ${STORAGE_CLASS_NAME}
            config:
              SOURCE_REGISTRY: "664529841144.dkr.ecr.us-west-2.amazonaws.com"
      flags:
        install: true
        createNamespace: false
        dependencyUpdate: true
    - name: artifactmanager
      namespace: ${NAMESPACE}
      repository:
        git:
          host: https://github.com/sasahoo-tibco/tp-integration.git
          path: /helm/charts/artifactmanager
          branch: main
      values:
        - content: |
            global:
              artifactmanager:
                data:
                  namspace: ${NAMESPACE}
                image:
                  registry: 664529841144.dkr.ecr.us-west-2.amazonaws.com
                  tag: 18-m1-ext
            ingress:
              annotations:
                haproxy.org/cors-enable: "true"
                haproxy.org/load-balance: leastconn
                haproxy.org/src-ip-header: X-Real-IP
                haproxy.org/timeout-http-request: 600s
                ingress.kubernetes.io/rewrite-target: /
                meta.helm.sh/release-name: artifactmanager
                meta.helm.sh/release-namespace: ${NAMESPACE}
              enabled: true
              hostsOverride: false
            volumes:
              artifactmanager:
                persistentVolumeClaim:
                  create: true
                  storageClassName: ${STORAGE_CLASS_NAME}
      flags:
        install: true
        createNamespace: false
        dependencyUpdate: true
    - name: apiserver
      namespace: ${NAMESPACE}
      repository:
        git:
          host: https://github.com/sasahoo-tibco/tp-integration.git
          path: /helm/charts/apiserver
          branch: main
      values:
        - content: |
            global:
              apiserver:
                data:
                  namspace: ${NAMESPACE}
                image:
                  registry: 664529841144.dkr.ecr.us-west-2.amazonaws.com
                  tag: 7-m1-ext
            ingress:
              annotations:
                haproxy.org/cors-enable: "true"
                haproxy.org/load-balance: leastconn
                haproxy.org/src-ip-header: X-Real-IP
                haproxy.org/timeout-http-request: 600s
                ingress.kubernetes.io/rewrite-target: /
                meta.helm.sh/release-name: apiserver
                meta.helm.sh/release-namespace: ${NAMESPACE}
              enabled: true
              hostsOverride: false
            ingressExternal:
              annotations:
                haproxy.org/cors-enable: "true"
                haproxy.org/load-balance: leastconn
                haproxy.org/src-ip-header: X-Real-IP
                haproxy.org/timeout-http-request: 600s
                ingress.kubernetes.io/rewrite-target: /
                meta.helm.sh/release-name: apiserver
                meta.helm.sh/release-namespace: ${NAMESPACE}
              enabled: true
              hosts:
                - host: ${EXTERNAL_HOST}
                  paths:
                  - path: /
                    pathType: Prefix
      flags:
        install: true
        createNamespace: false
        dependencyUpdate: true
        isDevTesting: false
status: deployed
region: us-west-2
tags:
  - Tag1
  - Tag2

