capabilityId: TETRIS
version: 1.0.0
recipe:
  helmCharts:
    - name: bwprovisioner
      namespace: tibco-dp-chdhd202p4g2r8ft6hf0
      repository:
        git:
          host: https://github.com/sasahoo-tibco/tp-integration.git
          path: /helm/charts/bwprovisioner
          branch: main
      values:
        - content: |
            global:
              bwprovisioner:
                data:
                  namspace: tibco-dp-chdhd202p4g2r8ft6hf0
                image:
                  registry: 664529841144.dkr.ecr.us-west-2.amazonaws.com
                  tag: 38-m1-ext
            ingress:
              annotations:
                haproxy.org/cors-enable: "true"
                haproxy.org/load-balance: leastconn
                haproxy.org/src-ip-header: X-Real-IP
                haproxy.org/timeout-http-request: 600s
                ingress.kubernetes.io/rewrite-target: /
                meta.helm.sh/release-name: bwprovisioner
                meta.helm.sh/release-namespace: tibco-dp-chdhd202p4g2r8ft6hf0
              enabled: true
              hostsOverride: false
            volumes:
              bwprovisioner:
                persistentVolumeClaim:
                  create: true
                  storageClassName: "gp2"
            config:
              #  DP_INTERNAL_URL: "test.tci-env.ap-southeast-2.tcie.pro"
              DP_INTERNAL_URL: "***NOT AVAILABLE***"
      flags:
        install: true
        createNamespace: false
        dependencyUpdate: true
    - name: artifactmanager
      namespace: tibco-dp-chdhd202p4g2r8ft6hf0
      repository:
        git:
          host: https://github.com/sasahoo-tibco/tp-integration.git
          path: /helm/charts/artifactmanager
          branch: main
      values:
        - content: |
            global:
              artifactmanager:
                data:
                  namspace: tibco-dp-chdhd202p4g2r8ft6hf0
                image:
                  registry: 664529841144.dkr.ecr.us-west-2.amazonaws.com
                  tag: 11-m1-ext
            ingress:
              annotations:
                haproxy.org/cors-enable: "true"
                haproxy.org/load-balance: leastconn
                haproxy.org/src-ip-header: X-Real-IP
                haproxy.org/timeout-http-request: 600s
                ingress.kubernetes.io/rewrite-target: /
                meta.helm.sh/release-name: artifactmanager
                meta.helm.sh/release-namespace: tibco-dp-chdhd202p4g2r8ft6hf0
              enabled: true
              hostsOverride: false
            volumes:
              artifactmanager:
                persistentVolumeClaim:
                  create: true
                  storageClassName: "gp2"
      flags:
        install: true
        createNamespace: false
        dependencyUpdate: true
    - name: apiserver
      namespace: tibco-dp-chdhd202p4g2r8ft6hf0
      repository:
        git:
          host: https://github.com/sasahoo-tibco/tp-integration.git
          path: /helm/charts/apiserver
          branch: main
      values:
        - content: |
            global:
              apiserver:
                data:
                  namspace: tibco-dp-chdhd202p4g2r8ft6hf0
                image:
                  registry: 664529841144.dkr.ecr.us-west-2.amazonaws.com
                  tag: 7-m1-ext
            ingress:
              annotations:
                haproxy.org/cors-enable: "true"
                haproxy.org/load-balance: leastconn
                haproxy.org/src-ip-header: X-Real-IP
                haproxy.org/timeout-http-request: 600s
                ingress.kubernetes.io/rewrite-target: /
                meta.helm.sh/release-name: apiserver
                meta.helm.sh/release-namespace: tibco-dp-chdhd202p4g2r8ft6hf0
              enabled: true
              hostsOverride: false
            ingressExternal:
              annotations:
                haproxy.org/cors-enable: "true"
                haproxy.org/load-balance: leastconn
                haproxy.org/src-ip-header: X-Real-IP
                haproxy.org/timeout-http-request: 600s
                ingress.kubernetes.io/rewrite-target: /
                meta.helm.sh/release-name: apiserver
                meta.helm.sh/release-namespace: tibco-dp-chdhd202p4g2r8ft6hf0
              enabled: true
              hosts:
                - host: "test.tci-env.us-west-2.tcie.pro"
                  paths:
                  - path: /
                    pathType: Prefix
      flags:
        install: true
        createNamespace: false
        dependencyUpdate: true
isDevTesting: true
status: deployed
region: us-west-2
tags:
  - Tag1
  - Tag2
