capabilityId: O11Y
version:
  - 1
  - 0
  - 0
recipe:
  helmCharts:
    - name: o11yservice
      namespace: ${NAMESPACE}
      repository:
        git:
          host: https://github.com/sasahoo-tibco/tp-integration.git
          path: /helm/charts/o11yservice
          branch: main
      values:
        - content: |
            global:
              o11yservice:
                image:
                  registry: 664529841144.dkr.ecr.us-west-2.amazonaws.com
                  tag: 112
            ingress:
              annotations:
                haproxy.org/cors-enable: "true"
                haproxy.org/load-balance: leastconn
                haproxy.org/src-ip-header: X-Real-IP
                haproxy.org/timeout-http-request: 600s
                ingress.kubernetes.io/rewrite-target: /
                meta.helm.sh/release-name: bwprovisioner
                meta.helm.sh/release-namespace: ${NAMESPACE}
              enabled: true
              hostsOverride: false
      flags:
        install: true
        createNamespace: false
        dependencyUpdate: true
        isDevTesting: false
status: deployed
region: us-west-2
tags:
  - Tag1
  - Tag2

