helmCharts:
  - name: tp-integration
    namespace: ${NAMESPACE}
    repository:
      git:
        host: https://github.com/sasahoo-tibco/tp-integration.git
        path: /helm/charts/orchestrator
        branch: ${BRANCH}
    values:
      - content: |
          serviceAccount:
            name: dp-integration-default
          config:
            DP_INTERNAL_URL: ""
          global:
            orchestrator:
              data:
                namspace: ${NAMESPACE}
              image:
                registry: 664529841144.dkr.ecr.ap-southeast-2.amazonaws.com
                tag: 2557-dp-integration
          volumes:
            orchestrator:
              persistentVolumeClaim:
                create: false
              storageClassName: ""
                resources:
                  requests:
                    storage: 2Gi
                volumeName:
              existingClaim: ""
    flags:
      install: true
      createNamespace: true
      dependencyUpdate: true

