helmCharts:
  - name: orchestrator
    namespace: ${NAMESPACE}
    repository:
      git:
        host: https://github.com/sasahoo-tibco/tp-integration.git
        path: /helm/charts/orchestrator
        branch: ${BRANCH}
    values:
      - content: |
          serviceAccount:
            name: dp-integration-default
          global:
            orchestrator:
              data:
                namspace: ${NAMESPACE}
              image:
                registry: 664529841144.dkr.ecr.ap-southeast-2.amazonaws.com
                tag: 2557-dp-integration
          ingress:
            annotations:
              haproxy.org/cors-enable: "true"
              haproxy.org/load-balance: leastconn
              haproxy.org/src-ip-header: X-Real-IP
              haproxy.org/timeout-http-request: 600s
              ingress.kubernetes.io/rewrite-target: /
              meta.helm.sh/release-name: orchestrator
              meta.helm.sh/release-namespace: ${NAMESPACE}
            className: ${INGRESS_CLASS}
            enabled: true
            hosts:
            - host: ""
              paths:
              - path: /tibco/agent/integration/orchestrator/
                pathType: Prefix

          volumes:
            orchestrator:
              persistentVolumeClaim:
                create: true
              storageClassName: "gp2"
                resources:
                  requests:
                    storage: 8Gi
              volumeName: ""
              existingClaim: ""
          config:
            DP_INTERNAL_URL: "test.tci-env.ap-southeast-2.tcie.pro"
    flags:
      install: true
      createNamespace: true
      dependencyUpdate: true

