{{- if eq .Values.global.bwprovisioner.serviceAccount "" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bwprovisioner.sa" . }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "bwprovisioner.role" . }}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get","list","watch","create","delete","patch","update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","list","watch","create","delete","patch","update"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get","list","watch","create","delete","patch","update"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get","list","watch","create","delete","patch","update"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get","list","watch","create","delete","patch","update"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get","list","watch","create","delete","patch","update"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "bwprovisioner.role-bind" . }}
subjects:
  - kind: ServiceAccount
    {{- if eq .Values.global.bwprovisioner.serviceAccount "" }}
    name: {{ include "bwprovisioner.sa" . }}
    {{- else }}
    name: {{ .Values.global.bwprovisioner.serviceAccount }}
    {{- end }}
roleRef:
  kind: Role
  name: {{ include "bwprovisioner.role" . }}
  apiGroup: rbac.authorization.k8s.io
