{{- if .Values.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bwprovisioner.sa" . }}
{{- end }}
---
{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "bwprovisioner.role" . }}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get","list","watch","create","delete","patch","update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","list","watch","create","delete","patch","update"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get","list","watch","create","delete","patch","update"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get","list","watch","create","delete","patch","update"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get","list","watch","create","delete","patch","update"]
{{- end }}
---
{{- if .Values.rbac.enabled }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "bwprovisioner.role-bind" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "bwprovisioner.sa" . }}
roleRef:
  kind: Role
  name: {{ include "bwprovisioner.role" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
