{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bwprovisioner.serviceAccountName" . }}
#  namespace: {{ .Values.global.bwprovisioner.data.namespace }}
  labels:
    {{- include "bwprovisioner.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
