apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dp-core-distributed-lock-operator.shared.func.globalResourcePrefix" . }}aggregate-to-admin
  labels:
    {{- include "dp-core-distributed-lock-operator.shared.labels.standard" . | nindent 4 }}
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  resourceNames:
  - tibcodistributedlocks.cloud.tibco.com
  verbs:
  - get
  - list
- apiGroups:
  - cloud.tibco.com
  resources:
  - tibcodistributedlocks
  verbs:
  - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dp-core-distributed-lock-operator.shared.func.globalResourcePrefix" . }}aggregate-to-view
  labels:
    {{- include "dp-core-distributed-lock-operator.shared.labels.standard" . | nindent 4 }}
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - cloud.tibco.com
  resources:
  - tibcodistributedlocks
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dp-core-distributed-lock-operator.shared.func.globalResourcePrefix" . }}aggregate-to-monitor
  labels:
    {{- include "dp-core-distributed-lock-operator.shared.labels.standard" . | nindent 4 }}
    rbac.authorization.k8s.io/aggregate-to-monitor: "true"
rules:
- apiGroups:
  - cloud.tibco.com
  resources:
  - tibcodistributedlocks
  verbs:
  - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dp-core-distributed-lock-operator.shared.func.globalResourcePrefix" . }}aggregate-to-tenant-ops
  labels:
    {{- include "dp-core-distributed-lock-operator.shared.labels.standard" . | nindent 4 }}
    rbac.authorization.k8s.io/aggregate-to-tenant-ops: "true"
rules:
- apiGroups:
  - cloud.tibco.com
  resources:
  - tibcodistributedlocks
  verbs:
  - "*"

### OPERATOR RBAC

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "dp-core-distributed-lock-operator.consts.appName" . }}
  labels:
    {{- include "dp-core-distributed-lock-operator.shared.labels.standard" . | nindent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "dp-core-distributed-lock-operator.shared.labels.standard" . | nindent 4 }}
  name: {{ include "dp-core-distributed-lock-operator.shared.func.globalResourcePrefix" . }}cr
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  resourceNames:
  - tibcodistributedlocks.cloud.tibco.com
  verbs:
  - get
  - list
- apiGroups:
  - cloud.tibco.com
  resources:
  - tibcodistributedlocks
  - tibcodistributedlocks/status
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
    - events
  verbs:
    - create
    - patch
{{- if .Values.highAvailabilityMode }}
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - '*'
{{- end }}

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "dp-core-distributed-lock-operator.shared.func.globalResourcePrefix" . }}crb
  labels:
    {{- include "dp-core-distributed-lock-operator.shared.labels.standard" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "dp-core-distributed-lock-operator.shared.func.globalResourcePrefix" . }}cr
subjects:
- kind: ServiceAccount
  name: {{ include "dp-core-distributed-lock-operator.consts.appName" . }}

