apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    {{- include "artifactmanager.labels" . | nindent 4 }}
  name: fluentbit-config-es
data:
  test: ""
#  {{ (.Files.Glob "config/es/fluent-bit.conf").AsConfig | indent 2 }}
#  {{ (.Files.Glob "config/es/input-tail.conf").AsConfig | indent 2 }}
#  {{ (.Files.Glob "config/es/parsers.conf").AsConfig | indent 2 }}
#  {{ (.Files.Glob "config/es/filters.conf").AsConfig | indent 2 }}
#  {{ (.Files.Glob "config/es/output-es.conf").AsConfig | indent 2 }}
