global:
  enableLogging: true
  serviceAccount: "" #user provided service account.
  image:
    registry: 664529841144.dkr.ecr.us-west-2.amazonaws.com
    tag: 58
  cp:
    dataplaneId: ""
    distlockoperator:
      serviceAccount: "" #user provided service account.

enableWebHooks: true

replicaCount: 1

settingsConfigmap:
  - key: "LOG_LEVEL"
    value: "info"
  - key: "LOCK_EXPIRY_DURATION"
    value: "2m"


